language: python
python:
      - "3.4"
      - "3.5"
      - "3.6"
before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y gdb
      - pip install pytest pytest-cov
      - pip install coveralls
install:
      - python setup.py install
script:
      - mkdir -p ~/.local/bin
      - touch ~/.local/bin/afl-fuzz
      - chmod +x ~/.local/bin/afl-fuzz
      - export PATH=$PATH:~/.local/bin/
      - coverage run setup.py test
after_success:
      - coveralls
